### ISSUE TITLE
Uncaught TypeError: _ref1.getUrl is not a function

### ISSUE THREAD

**Issue by fusion809** [skandasoft/browser-plus#91]
Hi,

[Enter steps to reproduce below:]
1. Open browser-plus using the right-click drop-down menu. 

**Atom Version**: 1.8.0
**Electron Version**: 1.2.6
**System**: "Arch Linux"
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.67
### Stack Trace

Uncaught TypeError: _ref1.getUrl is not a function

```
At /home/fusion809/.atom/packages/browser-plus/lib/browser-plus-view.coffee:405

TypeError: _ref1.getUrl is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.addHistory (/home/fusion809/.atom/packages/browser-plus/lib/browser-plus-view.coffee:405:22)
    at webview.<anonymous> (/home/fusion809/.atom/packages/browser-plus/lib/browser-plus-view.coffee:151:12)
    at WebViewImpl.dispatchEvent (/usr/lib/electron/resources/electron.asar/renderer/web-view/web-view.js:191:50)
    at dispatchEvent (/usr/lib/electron/resources/electron.asar/renderer/web-view/guest-view-internal.js:57:11)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/renderer/web-view/guest-view-internal.js:66:21)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
```
### Commands

```
  2x -3:50.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:49.6.0 core:save (atom-text-editor.editor.is-focused)
  8x -3:49 core:move-down (atom-text-editor.editor.is-focused.mini)
     -3:45.4.0 core:move-up (atom-text-editor.editor.is-focused)
 27x -3:27.1.0 core:backspace (atom-text-editor.editor.is-focused.mini)
  2x -3:22.2.0 core:save (atom-text-editor.editor.is-focused)
  7x -2:47.9.0 core:backspace (atom-text-editor.editor.is-focused.mini)
     -2:28.8.0 core:move-right (atom-text-editor.editor.is-focused.mini)
  9x -2:23.8.0 core:backspace (atom-text-editor.editor.is-focused.mini)
     -2:19.8.0 core:save (atom-text-editor.editor.is-focused.mini)
  6x -2:05.7.0 core:backspace (atom-text-editor.editor.is-focused.mini)
     -1:59.1.0 core:save (atom-text-editor.editor.is-focused.mini)
  6x -1:42.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:33.5.0 core:move-down (atom-text-editor.editor.is-focused)
 40x -1:30.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:12.6.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-gfm",
      "language-shellscript",
      "project-manager"
    ],
    "projectHome": "/home/fusion809/GitHub/mine",
    "themes": [
      "fusion-ui",
      "dark-bint-syntax"
    ]
  },
  "browser-plus": {
    "homepage": "browser-plus://localhost:4000",
    "live": 1
  }
}
```
### Installed Packages

``` coffee
# User
archive-view, v0.61.1 (active)
asciidoc-preview, v2.5.1 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (inactive)
atom-material-ui, v1.2.13 (inactive)
atom-oss-license, v1.0.0 (active)
autocomplete-asciidoc, v0.1.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-modules, v1.5.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-python, v1.8.1 (active)
autocomplete-sass, v0.1.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
browser-plus, v0.0.67 (active)
command-palette, v0.38.0 (inactive)
dark-bint-syntax, v0.8.9 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
file-icons, v1.7.16 (active)
find-and-replace, v0.201.0 (inactive)
fusion-ui, v0.11.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
git-plus, v5.16.2 (inactive)
git-time-machine, v1.5.3 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
language-archlinux, v0.5.3 (active)
language-asciidoc, v1.5.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.1 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.0 (active)
language-debian, v0.2.1 (active)
language-docker, v1.1.6 (active)
language-gentoo, v0.9.0 (active)
language-gfm2, v0.92.1 (active)
language-git, v0.14.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-ini-desktop, v1.18.3 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.1 (active)
language-less, v0.29.4 (active)
language-liquid, v0.5.1 (active)
language-lisp, v0.2.0 (active)
language-lua, v0.9.4 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-pascal, v0.18.1 (active)
language-patch2, v0.2.0 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.1 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-rpm-spec, v0.10.0 (active)
language-ruby, v0.68.6 (active)
language-ruby-on-rails, v0.25.0 (active)
language-rust, v0.4.6 (active)
language-sass, v0.55.0 (active)
language-scala, v1.1.6 (active)
language-solus, v0.2.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.22.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-unix-shell, v0.35.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)
line-ending-selector, v0.5.0 (active)
markdown-toc, v0.4.1 (inactive)
markdown-writer, v2.3.6 (active)
material-ui, v1.0.9 (inactive)
minimap, v4.24.7 (active)
monokai-flat, v1.0.1 (inactive)
notifications, v0.65.0 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
package-sync, v1.1.0 (active)
pigments, v0.31.0 (active)
snippets, v1.0.2 (active)
timecop, v0.33.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
dark-bint-syntax, v0.8.9 (active)
fusion-ui, v0.11.1 (active)
about-arch, v1.6.2 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
find-and-replace, v0.201.0 (inactive)
grammar-selector, v0.48.1 (active)
keybinding-resolver, v0.35.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
settings-view, v0.240.0 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.99.0 (active)
terminal-fusion, v2.2.3 (active)
tree-view, v0.208.0 (active)

# Dev
No dev packages
```

this error does not occur by itself, I will be creating one extra issue with these other errors. 

Thanks for your time,
Brenton

**Comment by skandasoft** [comment]
Please check the latest patch and feel free to reopen if the issue still exit

**Comment by fusion809** [comment]
I can't label this issue as opened, probably because I don't own this repo.

**Comment by skandasoft** [comment]
can you tell me the steps to reproduce this.  context menu on a file and open that file in browser-plus or context menu to just open the home page?

**Comment by fusion809** [comment]
All I did was, from the context menu, I selected "Open Browser-Plus" and this error occurred.

**Comment by 00buggy00** [comment]
I also got this error this morning after I upgraded to 1.12.1.  Last browser-plus was working without issues, then after upgrading, the error occurred when any new page was loaded.

"_ref1.getUrl is not a function" occurred with "_this.htmlv[0].getUrl is not a function"

**Comment by davidpgil** [comment]
Ive encountered this same issue as well.

**Comment by skandasoft** [comment]
Check the latest patch.

**Comment by davidpgil** [comment]
Error stil exists @skandasoft ... Here is the stack trace message i see:

TypeError: ref1.getUrl is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.addHistory (file:///C:/Users/davidpgil/.atom/packages/browser-plus/lib/browser-plus-view.coffee:446:22)
    at webview.<anonymous> (file:///C:/Users/davidpgil/.atom/packages/browser-plus/lib/browser-plus-view.coffee:155:12)
    at WebViewImpl.dispatchEvent (C:\Users\dgil\AppData\Local\atom\app-1.12.1\resources\electron.asar\renderer\web-view\web-view.js:192:29)
    at dispatchEvent (C:\Users\davidpgil\AppData\Local\atom\app-1.12.1\resources\electron.asar\renderer\web-view\guest-view-internal.js:57:11)
    at EventEmitter.<anonymous> (C:\Users\dgil\AppData\Local\atom\app-1.12.1\resources\electron.asar\renderer\web-view\guest-view-internal.js:66:21)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)

**Comment by skandasoft** [comment]
Quick fix in. but it is going to miss the icon. will update the better fix.soon
